fittings/urls.py
from django.urls import path
from django.conf.urls import url


from . import views

app_name = 'fittings'

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^fit/add/$', views.add_fit, name='add_fit'),
    url(r'^fit/all/$', views.view_all_fits, name='view_all_fits'),
    url(r'^fit/(?P<fit_id>[0-9]+)/$', views.view_fit, name='view_fit'),
    url(r'^fit/(?P<fit_id>[0-9]+)/delete/$', views.delete_fit, name='delete_fit'),
    url(r'^fit/(?P<fit_id>[0-9]+)/save/$', views.save_fit, name='save_fit'),
    url(r'^doctrine/add/$', views.add_doctrine, name='add_doctrine'),
    url(r'^doctrine/(?P<doctrine_id>[0-9]+)/$', views.view_doctrine, name='view_doctrine'),
    url(r'^doctrine/(?P<doctrine_id>[0-9]+)/delete/$', views.delete_doctrine, name='delete_doctrine'),
    url(r'^doctrine/(?P<doctrine_id>[0-9]+)/edit/$', views.edit_doctrine, name='edit_doctrine'),
]

fittings/templates/fittings/add_doctrine.html
{% extends 'fittings/base.html' %}
{% load i18n %}
{% load humanize %}
{% load filters %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/multi-select/0.9.12/css/multi-select.min.css" />
    <style>
        .form-control {
            margin: 2px;
        }

        .ms-container {
            width: 100% !important;
        }

    </style>

{% endblock %}

{% block page_title %}{% trans "Add Doctrine" %}{% endblock %}

{% block fittings_block %}
    {% if msg %}
            <div class="alert alert-{{ msg.0 }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    {% if msg.0 != 'warning' %}<h4>{% if msg.0 == 'danger' %}Oh No!{% elif msg.0 == 'success' %}Success!{% endif %}</h4>{% endif %}
                    <p>{{ msg.1 }}</p>
                </div>
        {% endif %}
    <div class="container col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                New Doctrine
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label">Doctrine Name</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="name" id="name" required/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="description" class="col-sm-2 control-label">Doctrine Description</label>
                                <div class="col-sm-10">
                                    <textarea class="form-control" name="description" id="description" rows="4"></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="fitSelect" class="col-sm-2 control-label">Select Fits</label>
                                <div class="col-sm-10" style="margin-top: 5px; margin-bottom: 5px;">
                                    <select multiple="multiple" id="fitSelect" name="fitSelect">
                                        {% for fit in fittings %}
                                            <option value="{{ fit.pk }}">{{ fit.name }} ({{fit.ship_type.type_name}})</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="iconSelect" class="col-sm-2 control-label">Select Doctrine Icon</label>
                                <div class="col-sm-10">
                                    <select class="form-control" name="iconSelect" id="iconSelect" aria-describedby="helpBlock">
                                        {% for ship in ships %}
                                            <option value="https://imageserver.eveonline.com/Type/{{ship.ship_type}}_64.png">{{ship.ship_type__type_name}}</option>
                                        {% endfor %}
                                    </select>
                                    <span id="helpBlock" class="help-block"> If you do not see the ship type that you would like to use for the icon, add a fit that uses that ship type and try again.</span>
                                </div>
                            </div>
                            <br />
                            <button class="btn btn-primary btn-block" type="submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/multi-select/0.9.12/js/jquery.multi-select.js" integrity="sha256-JU2QMhOvXGZtWxxkQTEgpVjdPHMYMuVYbYzNqfsioNw=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.quicksearch/2.4.0/jquery.quicksearch.min.js" integrity="sha256-hD1kpQcVntR40eMx9uED+E4HAjD2OJkLIFcP6ukVd+g=" crossorigin="anonymous"></script>
{% endblock %}

{% block extra_script %}
    $('#fitSelect').multiSelect({
          selectableHeader: "<input type='text' class='form-control' autocomplete='off' placeholder='Search' style='margin-bottom: 3px;'>",
          selectionHeader: "<input type='text' class='form-control' autocomplete='off' placeholder='Search' style='margin-bottom: 3px;'>",
          afterInit: function(ms){
            var that = this,
                $selectableSearch = that.$selectableUl.prev(),
                $selectionSearch = that.$selectionUl.prev(),
                selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
                selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

            that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
            .on('keydown', function(e){
              if (e.which === 40){
                that.$selectableUl.focus();
                return false;
              }
            });

            that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
            .on('keydown', function(e){
              if (e.which == 40){
                that.$selectionUl.focus();
                return false;
              }
            });
          },
          afterSelect: function(){
            this.qs1.cache();
            this.qs2.cache();
          },
          afterDeselect: function(){
            this.qs1.cache();
            this.qs2.cache();
          }
        })
{% endblock %}

fittings/templates/fittings/add_fit.html
{% extends 'fittings/base.html' %}
{% load i18n %}
{% load humanize %}
{% load filters %}

{% block page_title %}{% trans "Add Fit" %}{% endblock %}

{% block fittings_block %}
    {% if msg %}
            <div class="alert alert-{{ msg.0 }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    {% if msg.0 != 'warning' %}<h4>{% if msg.0 == 'danger' %}Oh No!{% elif msg.0 == 'success' %}Success!{% endif %}</h4>{% endif %}
                    <p>{{ msg.1 }}</p>
                </div>
        {% endif %}
    <div class="container col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Add Fitting
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="iconSelect" class="col-sm-2 control-label">Description</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="description" id="description" />
                                </div>
                            </div>
                            <br />
                            <div class="form-group" >
                                <label for="iconSelect" class="col-sm-2 control-label">Fit</label>
                                <div class="col-sm-10" style="margin-top: 5px; margin-bottom: 5px;">
                                    <textarea class="form-control" name="eft" id="eft" rows="10"></textarea>
                                </div>
                            </div>
                            <br />
                            <button class="btn btn-primary btn-block" type="submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

fittings/templates/fittings/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% block extra_css %}
    <style>
        .flex-container {
            display: flex;
            flex-direction: row;
            height: 100%;
            align-items: center;
            justify-content: center;
        }
        .flex-wrap {
            display: -webkit-flex; /* Safari */
            -webkit-flex-wrap: wrap; /* Safari 6.1+ */
            display: flex;
            flex-wrap: wrap;
        }
        .flex-item {

        }
    </style>
    {% include 'bundles/datatables-css.html' %}
{% endblock extra_css %}
{% block content %}
    <div class="col-lg-12">
        <br />
        <div class="col-lg-12 container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">{% trans "Toggle navigation" %}</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'fittings:dashboard' %}">{% trans "Fittings and Doctrines" %}</a>
                    </div>
                    <ul class="nav navbar-nav navbar-left">
                            <li> <a href="{% url 'fittings:view_all_fits' %}">View All Fits</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if perms.fittings.manage %}
                            <li> <a href="{% url 'fittings:add_fit' %}">Add Fitting</a></li>
                            <li> <a href="{% url 'fittings:add_doctrine' %}">Add Doctrine</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            {% block fittings_block %}{% endblock %}
        </div>
    </div>
{% endblock %}

fittings/templates/fittings/dashboard.html
{% extends 'fittings/base.html' %}
{% load i18n %}
{% load humanize %}
{% load filters %}
{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
{% endblock %}


{% block page_title %}{% trans "Dashboard" %}{% endblock %}

{% block fittings_block %}
    {% if msg %}
            <div class="alert alert-{{ msg.0 }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    {% if msg.0 != 'warning' %}<h4>{% if msg.0 == 'danger' %}Oh No!{% elif msg.0 == 'success' %}Success!{% endif %}</h4>{% endif %}
                    <p>{{ msg.1 }}</p>
                </div>
        {% endif %}
    <div class="container col-sm-12">
        <h2>
            Doctrine List
        </h2>
        <div class="panel panel-default">
            <div class="panel-heading">
                Doctrines
            </div>
            <div class="panel-body">
                <table class="table table-hover dataTable" id="docTable">
                    <thead>
                        <th> </th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Ships</th>
                    </thead>
                    <tbody>
                        {% if not docs %}
                            <tr>
                                <td colspan="4">
                                    <div class="alert alert-warning" style="text-align: center"> No Doctrines Found </div>
                                </td>
                            </tr>
                        {% else %}
                            {% for doc in docs %}
                                <tr>
                                    <td> <a href="{% url 'fittings:view_doctrine' doc.pk %}"><img src="{{ doc.icon_url }}" class="img-circle" style="display: block; margin: auto;"/> </a></td>
                                    <td> <a href="{% url 'fittings:view_doctrine' doc.pk %}">{{ doc.name }}</a> </td>
                                    <td> {{ doc.description }} </td>
                                    <td>
                                        {% for fitting in doc_dict|get_item:doc.pk %}
                                            <img src="https://imageserver.eveonline.com/Type/{{ fitting.ship_type_type_id }}_64.png" class="img-circle" style="height: 32px; width: 32px;" data-toggle="tooltip" data-placement="bottom" title="{{ fitting.ship_type.type_name }}"/>
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
{% endblock %}

{% block extra_script %}
    $(document).ready(function(){
        $('#docTable').DataTable();
        $('[data-toggle="tooltip"]').tooltip();
    })
{% endblock %}

fittings/templates/fittings/edit_doctrine.html
{% extends 'fittings/base.html' %}
{% load i18n %}
{% load humanize %}
{% load filters %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/multi-select/0.9.12/css/multi-select.min.css" />
    <style>
        .form-control {
            margin: 2px;
        }
        .ms-container {
            width: 100% !important;
        }

    </style>

{% endblock %}

{% block page_title %}{% trans "Add Doctrine" %}{% endblock %}

{% block fittings_block %}
    {% if msg %}
            <div class="alert alert-{{ msg.0 }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    {% if msg.0 != 'warning' %}<h4>{% if msg.0 == 'danger' %}Oh No!{% elif msg.0 == 'success' %}Success!{% endif %}</h4>{% endif %}
                    <p>{{ msg.1 }}</p>
                </div>
        {% endif %}
    <div class="container col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                New Doctrine
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label">Doctrine Name</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="name" id="name" value="{{ doctrine.name }}" required/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="description" class="col-sm-2 control-label">Doctrine Description</label>
                                <div class="col-sm-10">
                                    <textarea class="form-control" name="description" id="description" rows="4">{{ doctrine.description }}</textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="fitSelect" class="col-sm-2 control-label">Select Fits</label>
                                <div class="col-sm-10" style="margin-top: 5px; margin-bottom: 5px;">
                                    <select multiple="multiple" id="fitSelect" name="fitSelect">
                                        {% for fit in doc_fits %}
                                            <option value="{{ fit.pk }}" selected>{{ fit.name }} ({{ fit.ship_type.type_name }})</option>
                                        {% endfor %}
                                        {% for fit in fits %}
                                            <option value="{{ fit.pk }}">{{ fit.name }} ({{fit.ship_type.type_name}})</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="iconSelect" class="col-sm-2 control-label">Select Doctrine Icon</label>
                                <div class="col-sm-10">
                                    <select class="form-control" name="iconSelect" id="iconSelect" aria-describedby="helpBlock">
                                        <option value="{{ doctrine.icon_url }}" selected> Current Icon </option>
                                        {% for ship in ships %}
                                            <option value="https://imageserver.eveonline.com/Type/{{ship.ship_type}}_64.png">{{ship.ship_type__type_name}}</option>
                                        {% endfor %}
                                    </select>
                                    <span id="helpBlock" class="help-block"> If you do not see the ship type that you would like to use for the icon, add a fit that uses that ship type and try again.</span>
                                </div>
                            </div>
                            <br />
                            <button class="btn btn-primary btn-block" type="submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/multi-select/0.9.12/js/jquery.multi-select.js" integrity="sha256-JU2QMhOvXGZtWxxkQTEgpVjdPHMYMuVYbYzNqfsioNw=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.quicksearch/2.4.0/jquery.quicksearch.min.js" integrity="sha256-hD1kpQcVntR40eMx9uED+E4HAjD2OJkLIFcP6ukVd+g=" crossorigin="anonymous"></script>
{% endblock %}

{% block extra_script %}
    $('#fitSelect').multiSelect({
          selectableHeader: "<input type='text' class='form-control' autocomplete='off' placeholder='Search' style='margin-bottom: 3px;'>",
          selectionHeader: "<input type='text' class='form-control' autocomplete='off' placeholder='Search' style='margin-bottom: 3px;'>",
          afterInit: function(ms){
            var that = this,
                $selectableSearch = that.$selectableUl.prev(),
                $selectionSearch = that.$selectionUl.prev(),
                selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
                selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

            that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
            .on('keydown', function(e){
              if (e.which === 40){
                that.$selectableUl.focus();
                return false;
              }
            });

            that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
            .on('keydown', function(e){
              if (e.which == 40){
                that.$selectionUl.focus();
                return false;
              }
            });
          },
          afterSelect: function(){
            this.qs1.cache();
            this.qs2.cache();
          },
          afterDeselect: function(){
            this.qs1.cache();
            this.qs2.cache();
          }
        })
{% endblock %}

fittings/templates/fittings/view_all_fits.html
{% extends 'fittings/base.html' %}
{% load i18n %}
{% load humanize %}
{% load filters %}
{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
{% endblock %}


{% block page_title %}{% trans "View All Fits" %}{% endblock %}

{% block fittings_block %}
    {% if msg %}
            <div class="alert alert-{{ msg.0 }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times</span>
                    </button>
                    {% if msg.0 != 'warning' %}<h4>{% if msg.0 == 'danger' %}Oh No!{% elif msg.0 == 'success' %}Success!{% endif %}</h4>{% endif %}
                    <p>{{ msg.1 }}</p>
                </div>
        {% endif %}
    <div class="container col-sm-12">
        <h2>
            Fit List
        </h2>
        <div class="panel panel-default">
            <div class="panel-heading">
                Fits
            </div>
            <div class="panel-body">
                <table class="table table-hover dataTable" id="fitTable">
                    <thead>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Ship Type</th>
                    </thead>
                    <tbody>
                        {% if not fits %}
                            <tr>
                                <td colspan="4">
                                    <div class="alert alert-warning" style="text-align: center"> No Fits Found </div>
                                </td>
                            </tr>
                        {% else %}
                            {% for fit in fits %}
                                <tr>
                                    <td> <a href="{% url 'fittings:view_fit' fit.pk %}">{{ fit.name }}</a> </td>
                                    <td> {{ fit.description }} </td>
                                    <td> {% item_img_circle fit.ship_type_type_id fit.ship_type.name '32' %} {{ fit.ship_type.type_name }} </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
{% endblock %}

{% block extra_script %}
    $(document).ready(function(){
        $('#fitTable').DataTable();
        $('[data-toggle="tooltip"]').tooltip();
    })
{% endblock %}

fittings/templates/fittings/view_doctrine.html
{% extends 'fittings/base.html' %}
{% load i18n %}
{% load humanize %}
{% load filters %}
{% load static %}
{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
{% endblock %}

{% block page_title %}{{ doctrine.name }} {% trans "Doctrine" %}{% endblock %}

{% block fittings_block %}
    {# modal start #}
    <div class="modal fade" id="deleteModal" role="dialog" tabindex="-1" aria-labelledby="modalTitle">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="modalTitle">Are you sure?</h4>
                </div>
                <div class="modal-body">
                    <p style="white-space: pre-line">Are you sure you wish to delete this doctrine?

                        <i><strong>This action is permanent.</strong></i></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No - Close</button>
                    <a href="{% url 'fittings:delete_doctrine' doctrine.pk %}" type="button" class="btn btn-danger">Yes - Delete</a>
                </div>
            </div>
        </div>
    </div>

    {# modal end #}
    <br />
    <div class="col-md-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Doctrine Information
                {% if perms.fittings.manage %}
                    <span data-toggle="modal" data-target="#deleteModal">
                        <button class="btn btn-xs btn-danger" style="float: right; margin-left: 5px;" data-toggle="tooltip" data-placement="top" title="Delete Doctrine"><span class="fa fa-times"></span> </button>
                    </span>
                    <a href="{% url 'fittings:edit_doctrine' doctrine.pk %}" class="btn btn-xs btn-warning" style="float: right" data-toggle="tooltip" data-placement="top" title="Edit Doctrine"><span class="fa fa-pencil"></span> </a>
                {% endif %}
            </div>
            <div class="panel-body">
                <img src="{{ doctrine.icon_url }}" class="img-circle center-block" style="text-align: center"/>
                <h4 style="text-align: center">{{ doctrine.name }}</h4>
                <hr />
                <dl>
                    <dt>Description</dt>
                    <dd>{{ doctrine.description }}</dd>
                    <dt>Created</dt>
                    <dd>{{ doctrine.created|date:'d M Y H:i:s' }}</dd>
                    {% if doctrine.last_updated %}
                        <dt>Last Updated</dt>
                        <dd>{{ doctrine.last_updated|date:'d M Y H:i:s' }}</dd>
                    {% endif %}
                </dl>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">Doctrine Fits</div>
            <div class="panel-body">
                <table class="table table-hover dataTable" id="fitsTable">
                    <thead>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Ship Type</th>
                    </thead>
                    <tbody>
                        {% if not fits %}
                            <tr>
                                <td colspan="4">
                                    <div class="alert alert-warning" style="text-align: center"> No Fits Found </div>
                                </td>
                            </tr>
                        {% else %}
                            {% for fit in fits %}
                                <tr>
                                    <td> <a href="{% url 'fittings:view_fit' fit.pk %}">{{ fit.name }}</a> </td>
                                    <td> {{ fit.description }} </td>
                                    <td> {% item_img_circle fit.ship_type_type_id fit.ship_type.name '32' %} {{ fit.ship_type.type_name }}</td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
{% endblock %}

{% block extra_script %}
     $(document).ready(function(){
        $('#fitsTable').DataTable();
        $('[data-toggle="tooltip"]').tooltip();
    })
{% endblock %}